spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    username: postgres
    password: Inushing1980
    driverClassName: org.postgresql.Driver

#      url: jdbc:h2:mem:intershop
#      username: user
#      password:
#      driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  sql:
    init.mode: always
  jpa:
    open-in-view: false
#    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    properties.hibernate:
      show_sql: false
      format_sql: true
      highlight_sql: true
      jdbc.batch_size: 20
      order_updates: true
      cache:
        use_second_level_cache: false
        region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  #        provider_class: org.ehcache.jsr107.EhcacheCachingProvider
  transaction:
    default-timeout: 3
    rollback-on-commit-failure: true

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: INFO

application:
  items.perline: 3