spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/intershop
    username: ${username}
    password: ${password}
    driverClassName: org.postgresql.Driver
  sql:
    init.mode: always
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
    properties.hibernate:
      show_sql: false
      format_sql: true
      highlight_sql: true
      jdbc.batch_size: 20
      order_updates: true
      cache:
        use_second_level_cache: true
        region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  transaction:
    default-timeout: 3
    rollback-on-commit-failure: true

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: DEBUG
    org.zalando.logbook: DEBUG

application:
  user_id: 1  #  id текущего пользователя
  items:
    perline: 3  #  количество товаров в одном ряду
    load.enabled: true  #  включена возможность загрузки товаров через административную панель
    images.directory: c:/temp/imageStorage   #  директория для хранения загруженных картинок
